### ISSUE TITLE
 出现一个重大bug，只要你添加HttpLoggingInterceptor，这个log拦截器就会报错 

### ISSUE THREAD

**Issue by LLQQHH** [18702953620/MVPDemo#2]
![image](https://user-images.githubusercontent.com/19651932/55769739-6b296980-5ab4-11e9-8738-029e4034d3ea.png)
大概意思就是，请求已经被丢弃了，但是你还要打印log所以报错了

**Comment by LLQQHH** [comment]
只是加了这个步骤而已 
OkHttpClient.Builder builder = new OkHttpClient.Builder();
        //设置拦截器
       // builder.addInterceptor(interceptor);
        builder.addInterceptor(new HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY));
我去BasePresenter，把请求加入到compositeDisposable的方法去掉就不会报错了，所以问题就是出现在这里，但是就是不知道如何解决！
因为我们确实得请求加入到compositeDisposable，以防请求回来界面已经关闭！

**Comment by 18702953620** [comment]
建议你看看HttpLoggingInterceptor怎么用
